### ISSUE TITLE
Please add more movies and series of years

### ISSUE THREAD

**Issue by Doctor2023** [devlocalhost/moviepy#1]
Hello friend Please add more movies and series each year thanks to this 2023 changes and improvements

**Comment by devlocalhost** [comment]
hi. i dont really understand your request. are you asking me to add a category that shows movies and series by year? or upload more movies?

if you mean the first one (sort movies by year): that could be a little bit difficult, but i can give it a try
if you mean the second one (upload more movies): that is not possible. i am not the owner of the websites my code (moviepy) makes requests to. but, theres an reddit community, so you can request movies there: https://www.reddit.com/r/reqworkers101/

**Comment by Doctor2023** [comment]
> hi. i dont really understand your request. are you asking me to add a category that shows movies and series by year? or upload more movies?
> 
> if you mean the first one (sort movies by year): that could be a little bit difficult, but i can give it a try if you mean the second one (upload more movies): that is not possible. i am not the owner of the websites my code (moviepy) makes requests to. but, theres an reddit community, so you can request movies there: https://www.reddit.com/r/reqworkers101/

ok friend I understand then I enter that link and I can make requests for movies and series on the reddit page

**Comment by devlocalhost** [comment]
> > hi. i dont really understand your request. are you asking me to add a category that shows movies and series by year? or upload more movies?
> > if you mean the first one (sort movies by year): that could be a little bit difficult, but i can give it a try if you mean the second one (upload more movies): that is not possible. i am not the owner of the websites my code (moviepy) makes requests to. but, theres an reddit community, so you can request movies there: https://www.reddit.com/r/reqworkers101/
> 
> ok friend I understand then I enter that link and I can make requests for movies and series on the reddit page

Yes, exactly. Or, you could use other websites like 1337x, or you can check FMHY for other free movie/series websites: https://fmhy.pages.dev/beginners-guide#streaming
