### ISSUE TITLE
You can implement anime dramas korean  cartoon tv soaps  on the index page

### ISSUE THREAD

**Issue by Doctor2023** [devlocalhost/moviepy#3]
Hello friend Please implement anime and cartoon and  dramas Korean  and TV soaps

**Comment by devlocalhost** [comment]
As I've previously said in a older issue (https://github.com/devlocalhost/moviepy/issues/1#issuecomment-1816659868), I cannot do anything about that. I am not the owner of those websites, I do not have access to them
