### ISSUE TITLE
Please can you implement anime  and cartoons

### ISSUE THREAD

**Issue by Doctor2023** [devlocalhost/moviepy#5]
![IMG_0843](https://github.com/devlocalhost/moviepy/assets/129991276/a90e66fb-0fbf-4c98-8d25-b6771d36127b)

Please can you put an option of anime and cartoons like kdrama movies tv series 

changes this year 2024 and improvements indexes

**Comment by devlocalhost** [comment]
Im afraid I can't continue this anymore, honestly
